// Mocks generated by Mockito 5.4.5 from annotations
// in scan_book/test/viewmodels/mock_upload_service.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:io' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:scan_book/models/UploadResponse.dart' as _i2;
import 'package:scan_book/services/upload_service.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUploadResponse_0 extends _i1.SmartFake
    implements _i2.UploadResponse {
  _FakeUploadResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [UploadService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUploadService extends _i1.Mock implements _i3.UploadService {
  MockUploadService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.UploadResponse> uploadImages(List<_i5.File>? images) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadImages,
          [images],
        ),
        returnValue: _i4.Future<_i2.UploadResponse>.value(_FakeUploadResponse_0(
          this,
          Invocation.method(
            #uploadImages,
            [images],
          ),
        )),
      ) as _i4.Future<_i2.UploadResponse>);
}
