// Mocks generated by Mockito 5.4.5 from annotations
// in scan_book/test/viewmodels/scan_history_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:scan_book/models/history_request.dart' as _i4;
import 'package:scan_book/services/history_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [HistoryService].
///
/// See the documentation for Mockito's code generation for more information.
class MockHistoryService extends _i1.Mock implements _i2.HistoryService {
  MockHistoryService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Scan>> getScanHistory() => (super.noSuchMethod(
        Invocation.method(
          #getScanHistory,
          [],
        ),
        returnValue: _i3.Future<List<_i4.Scan>>.value(<_i4.Scan>[]),
      ) as _i3.Future<List<_i4.Scan>>);

  @override
  _i3.Future<void> deleteScans(List<int>? scanIds) => (super.noSuchMethod(
        Invocation.method(
          #deleteScans,
          [scanIds],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
